### ISSUE TITLE
Cannot instantiate union types without specifying the type literal

### ISSUE THREAD

**Issue by jettdc** [palantir/foundry-platform-python#49]
```
string_type = StringType()
```

is invalid, you need to do

```
string_type = StringType(type="string")
```
which is redundant

**Proposed solution:** Add a default val for literals

something like
```
class StringType(pydantic.BaseModel):
    type: Literal["string"] = Field(default="string")
    ...
```

**Comment by jettdc** [comment]
This also applies to things like 
```
FullRowChangeDataCaptureConfiguration(type="fullRow", ...)
```
which should not be necessary, as there is only one valid value there and the class itself should be enough context

**Comment by jsmith** [comment]
This is now resolved! For unions, we now default the `"type"` literal to the value.
