### ISSUE TITLE
Cannot use alias types directly 

### ISSUE THREAD

**Issue by jettdc** [palantir/foundry-platform-python#51]
Not sure if there is a better way to do this/if it's possible with pydantic, but currently you cannot directly intantiate/pass alias types

If you have the definition
```
Record = Dict[str, Any]
```

and something takes that as an input:
```
def some_method(record: Record):
  ...
```

I don't know how you actually instantiate that object, since this is invalid:
```
Record({"test": 2})
```

you just have to pass the raw dict currently. Could we modify to allow either:

```
def some_method(param: Record):
   ...

some_method(Record({"test": 2}))
some_method({"test": 2})
```
?

**Comment by jsmith** [comment]
For types like `Dict[str, Any]` the only option will be to specify the raw dict. For `TypedDict` classes such as the `CreateScheduleRequestActionDict`
https://github.com/palantir/foundry-platform-python/blob/e8f950b96ca9080b2b3ff3d579bf7352cd46233d/foundry/v2/orchestration/models/_create_schedule_request_action_dict.py#L35

you can instantiate it like this:

```
from foundry.v2.orchestration.models import CreateScheduleRequestActionDict

CreateScheduleRequestActionDict(
    target=...,
    abortOnFailure=...,
    forceBuild=...,
    retryBackoffDuration=...,
    retryCount=...,
    fallbackBranches=...,
    branchName=...,
    notificationsEnabled=...,
)
```
